### ISSUE TITLE
Feature Enhancement: Nomad Binary Version Management

### ISSUE THREAD

**Issue by ChefAustin** [mr-karan/nomctx#8]
This might not be in-scope of the vision for `nomctx` but I think its use-case is tangentially-related-enough that it is worth mentioning here. Feel free to swat this idea down if it does not align with this project's vision. That said...

I think it would be pretty neat if `nomctx` had the capacity to manage/use specific versions of the `nomad` binary itself (a la [`nvm` for Node](https://github.com/nvm-sh/nvm) or [`rvm` for Ruby](https://rvm.io/) or one of the many other `<x>vm`-style  projects).

I would imagine this could coalesce into the `nomctx` configuration file as such (using [this project's sample configuration](https://github.com/mr-karan/nomctx?tab=readme-ov-file#configuration) as an example):
``` hcl
cluster "dev" {
  address      = "http://127.0.0.1:4646"
  namespace = "default"
  version        = "1.7.6"
}

cluster "uat" {
  address = "https://nomad.hashicorp.rocks"
  auth {
    method  = "gitlab"
    provider = "nomad"
  }
  version      = "1.7.5+ent"
}

cluster "prod" {
  address   = "http://10.0.0.3:4646"
  namespace = "blue"
  region    = "blr"
  token     = "f8cb5774-749a-4548-acc9-054df3b52e83"
  version  = "1.7.4
}
```

I think it would be kind of cool if `nomctx` could automatically handle using a specific `nomad` version for a specific cluster. Much like `tfenv` (or most any other binary version management helper utility), this could include niceties like automated installation of a defined `nomad` version (from the `nomctx` config file) as well as modifying symlinks (or any similar such mechanism for moving between `nomad` versions when there are cluster context changes that require a new/different version).

**Comment by mr-karan** [comment]
Hi @ChefAustin ! Thanks a lot for showing interest in this project. `nomctx` goal is to simply provide helper utilities to login/manage a Nomad cluster. `nomctx` itself doesn't run any Nomad specific commands, so I am not sure where exactly does managing versions of `nomad` binary fits here.

Also, `nomad` can be installed with different package managers and other installation methods, not sure why `nomctx` will do that.

If you've any practical usecases in mind, where `nomctx` could help with different versions of `nomad`, please share here. Otherwise, as you'd rightly pointed out in the beginning, this feels a bit out of scope for this project to me.

Thanks!
